### ISSUE TITLE
respect the license

### ISSUE THREAD

**Issue by Orbmu2k** [DeadManWalkingTO/NVidiaProfileInspectorDmW#1]
@DarkStarSword already noticed to you, theres only one condition in the MIT license, to keep the copyright!

so please respect that and change the copyright back within the next seven days from now. otherwise i have to file a DMCA takedown to this fork.

**Comment by DeadManWalkingTO** [comment]
OMG! Yes i am sorry. (New to github! many thinks to learn!). I change the license file. If you need anything else just say.

**Comment by DeadManWalkingTO** [comment]
I delete all tags & releases with wrong license.
*Is there anything else to do?
(Thank you for your understanding. GitHub Newbie here;-))

**Comment by DeadManWalkingTO** [comment]
If your issue has solved, please close it.
Thank you very much.

**Comment by DeadManWalkingTO** [comment]
Now it's solved with [523ae89](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW/commit/523ae893b6dbcc1ee65bea2d3d1da0b36c70c9b9).
