### ISSUE TITLE
Save window size (or revert old commit)

### ISSUE THREAD

**Issue by DAOWAce** [DeadManWalkingTO/NVidiaProfileInspectorDmW#10]
Any chance you can implement window size saving?

If not, what about reverting the commit that reduced the default window size? https://github.com/Orbmu2k/nvidiaProfileInspector/commit/58a52d2656c34c98ba3bd054025d7563a078caac

Been my # 1 annoyance with the program ever since that version.

**Comment by DeadManWalkingTO** [comment]
Please give me few days. Thank you!

**Comment by DeadManWalkingTO** [comment]
Now it's ok.
Thank you!
