### ISSUE TITLE
Application opens, but the window is not visible

### ISSUE THREAD

**Issue by PrMinisterGR** [DeadManWalkingTO/NVidiaProfileInspectorDmW#12]
As the title says, the program no longer shows its window at all, after opening. I can see loading in the taskbar, and when I hover it is there (as it is when alt-tabbing), but the window itself or its contents never show.

It was working ok and it just stopped at a point.

That's on Windows 10 1809.

![image](https://user-images.githubusercontent.com/12447314/48986833-c2d4c300-f119-11e8-8a25-e1eabaf6f25e.png)

**Comment by DeadManWalkingTO** [comment]
Try update/reinstall .NET framework and feedback please!

**Comment by PrMinisterGR** [comment]
It appears that the issue was the application window going out of
sight.

**Comment by DeadManWalkingTO** [comment]
Give me some time please.
Thank you!

**Comment by XxFri3ndlyxX** [comment]
I had this issue today and all you have to do is download this app https://patchmypc.com/home-updater-download and download/update all microsoft runtime C++ along with both net framework and microsoft silver. So this is not a bug. It's only because you don't have the appropriate software installed.

**Comment by XxFri3ndlyxX** [comment]
Nevermind what i said above. Geforce experience updated and it's now doing this issue.

**Comment by DeadManWalkingTO** [comment]
Please check now.

**Comment by XxFri3ndlyxX** [comment]
> Please check now.

Seems to be working properly now. Thanks. Will reply back later to see if the bug comes back or not.  Thanks for the update!
