### ISSUE TITLE
Same as the below issue but alt tab reveals a black inspector with only the header bar

### ISSUE THREAD

**Issue by LethalManBoob** [DeadManWalkingTO/NVidiaProfileInspectorDmW#13]
Ive tried reinstalling net framework 7.2 but nothing. It used to work before

**Comment by LethalManBoob** [comment]
Please? Something? The guy said it was the thing going off screen but im not sure how to fix that.

**Comment by DeadManWalkingTO** [comment]
Give me some time please.
I believe it's the same issue (#12)
Thank you!

**Comment by LethalManBoob** [comment]
It still doesnt work. Any news on progress?

**Comment by DeadManWalkingTO** [comment]
Please check now.

**Comment by LethalManBoob** [comment]
Completely solved. Meany thanks!
