### ISSUE TITLE
Virus in NVidiaProfileInspectorDmW-v3.3.6.2-Windows.zip

### ISSUE THREAD

**Issue by RonnieDilli** [DeadManWalkingTO/NVidiaProfileInspectorDmW#14]
Windows Defender detected the virus "Trojan:Win32/Cloxer.D!cl" in the executable file.

**Comment by DeadManWalkingTO** [comment]
False alarm!
Program is Open Source.
Everyone can see the code.

**Comment by DeadManWalkingTO** [comment]
Is your system virus-free?
Was it infected during compile?
Is there anyone else that have the same issue?

**Comment by believer-ufa** [comment]
I have same issue: https://github.com/Orbmu2k/nvidiaProfileInspector/issues/28.

**Comment by believer-ufa** [comment]
Strange, but now everything is clean.

**Comment by LethalManBoob** [comment]
I sent my own built version of vanilla inspector to a friend and it was signed as a trojan but it was clean.
