### ISSUE TITLE
Any changes to backport to https://github.com/Orbmu2k/nvidiaProfileInspector

### ISSUE THREAD

**Issue by ValZapod** [DeadManWalkingTO/NVidiaProfileInspectorDmW#19]
Hello! Is there anything you want to backport to upstream? Maybe some memory leaks or some functionality?

**Comment by DeadManWalkingTO** [comment]
NVidiaProfileInspectorDmW is a Fork from Orbmu2k/nvidiaProfileInspector for full optimization that increase hashrate on NVidia graphic cards (GPU mining).
For all other reasons please use the original Orbmu2k/nvidiaProfileInspector repo (It's simply the best).

**Comment by ValZapod** [comment]
> for full optimization that increase hashrate

So maybe those changes? I mean there were already some idiots who complain about that https://github.com/Orbmu2k/nvidiaProfileInspector/issues/37
It is your site, right?)))

**Comment by DeadManWalkingTO** [comment]
I don't have a website. The only safe way to download any of my projects is GitHub.

**Comment by ValZapod** [comment]
That is interesting, thanks. I will close this issue then))
