### ISSUE TITLE
MSBUILD : error MSB1009: файл проекта не существует. Ключ: nvidiaProfileInspectorDmW.sln

### ISSUE THREAD

**Issue by abc-Status** [DeadManWalkingTO/NVidiaProfileInspectorDmW#4]
Я пытаюсь  разобраться  как  ребенок  ни  чего не понимаю.  можешь ты   объяснять нам как детям ?
MSBUILD : error MSB1009: файл проекта не существует.
Ключ: nvidiaProfileInspectorDmW.sln

**Comment by DeadManWalkingTO** [comment]
Please reopen the issue in English.
Thank you!

**Comment by abc-Status** [comment]
Google help you take yes Translate

**Comment by abc-Status** [comment]
I'm trying to figure out how the child does not understand. can you tell us how to children?
