### ISSUE TITLE
What's the point of this git repository?

### ISSUE THREAD

**Issue by Freekers** [DeadManWalkingTO/NVidiaProfileInspectorDmW#5]
The only thing you did was change some version numbers, change some assemblynames to 'DmW', removed trailing zeros in values (why???) and create a CustomSettingNames.xml, which, as pointed out by @DarkStarSword, doesn't require any code changes at all!

To me it feels like you're claiming @Orbmu2k's work as your own, in order to beg for donations.
I suggest you take this repo down, or restore the copyright notice the way it was or you risk having this taken down by DMCA.

**Comment by DeadManWalkingTO** [comment]
- This is a Fork from Orbmu2k/nvidiaProfileInspector.
- Any credits / cc are @Orbmu2k's. (Check licence.)
- I have contact with @Orbmu2k about that.
- I have completely rewrite CustomSettingNames.xml.
- I have add a lot of new settings.
- As i say at start "This is a Fork from Orbmu2k/nvidiaProfileInspector."

Thank you!
