### ISSUE TITLE
P0 state ubuntu

### ISSUE THREAD

**Issue by be4i** [DeadManWalkingTO/NVidiaProfileInspectorDmW#7]
Hello,
how i can set "P2 state force" to "off" in ubuntu ?

i have tried `nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1`

i also have found [this](https://forums.geforce.com/default/topic/1038627/geforce-drivers/setting-specific-driver-parameters-in-linux/)

**Comment by DeadManWalkingTO** [comment]
NVidiaProfileInspectorDmW run on Windows only.
